## Numpy array operations

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"Arr : {arr}")
print(f"Basic slicing : {arr[2:7]}")
print(f"With step : {arr[1:8:2]}")
print(f"Negative indexing : {arr[-3]}")

Arr : [1 2 3 4 5 6 7 8 9]
Basic slicing : [3 4 5 6 7]
With step : [2 4 6 8]
Negative indexing : 7


In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"2D Array :\n{arr_2d}")
print(f"\nSpecific element : {arr_2d[1, 2]}")
print(f"\nEntire row (1st) : {arr_2d[1]}")
print(f"\nEntire column (1st) : {arr_2d[:, 1]}")

2D Array :
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Specific element : 6

Entire row (1st) : [4 5 6]

Entire column (1st) : [2 5 8]


## Sorting

In [4]:
unsorted = np.array([3, 5, 2, 9, 6, 4, 2, 1, 4, 3, 8])
print(f"Unsorted : {unsorted}")
print(f"Sorted : {np.sort(unsorted)}")

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print(f"\n2D array unsorted :\n{arr_2d_unsorted}")
print(f"\nSorted 2D array by column :\n{np.sort(arr_2d_unsorted, axis=0)}")
print(f"\nSorted 2D array by row :\n{np.sort(arr_2d_unsorted, axis=1)}")

Unsorted : [3 5 2 9 6 4 2 1 4 3 8]
Sorted : [1 2 2 3 3 4 4 5 6 8 9]

2D array unsorted :
[[3 1]
 [1 2]
 [2 3]]

Sorted 2D array by column :
[[1 1]
 [2 2]
 [3 3]]

Sorted 2D array by row :
[[1 3]
 [1 2]
 [2 3]]


## Filter

In [5]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print(f"Even numbers : {even_number}")

Even numbers : [ 2  4  6  8 10]


## Filter with Mask

In [7]:
mask = numbers > 5
print(f"Numbers greater than 5 : {numbers[mask]}")

Numbers greater than 5 : [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [13]:
indices = [0, 2, 4]
print(f"{numbers}")
print(f"{numbers[indices]}")

where_result = np.where(numbers > 5)
print(where_result)
print(f"NP where : {numbers[where_result]}")

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where : [ 6  7  8  9 10]


In [23]:
condition_array1 = np.where(numbers > 5, numbers*10, numbers)
condition_array2 = np.where(numbers > 5, "True", "False")
print(F"C. Arr 1 : {condition_array1}")
print(F"C. Arr 2 : {condition_array2}")

C. Arr 1 : [  1   2   3   4   5  60  70  80  90 100]
C. Arr 2 : ['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


### Adding and Removing data

In [27]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# combined = arr1 + arr2

combined = np.concatenate((arr1, arr2))
print(f"Concatinated : {combined}")

Concatinated : [1 2 3 4 5 6]


### Array compatibility

In [30]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9, 10])

print(f"Compatibility shape : {a.shape == b.shape}")
print(f"Compatibility shape : {a.shape == c.shape}")

Compatibility shape : True
Compatibility shape : False


In [33]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print(f"Original:\n{original}")
print(f"\nWith new row:\n{with_new_row}")

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print(f"\nWith new column:\n{with_new_col}")

Original:
[[1 2]
 [3 4]]

With new row:
[[1 2]
 [3 4]
 [5 6]]

With new column:
[[1 2 7]
 [3 4 8]]


In [39]:
arr = np.array([1, 2, 3, 4 , 5])
deleted = np.delete(arr, 2)
print(f"Array after deletion : {deleted}")

Array after deletion : [1 2 4 5]
