## Numpy array and basics
### Learn about numpy with chai aur code

In [1]:
import numpy as np

### Creating array from list

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"1D Array : {arr_1d}")

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D Array : {arr_2d}")

1D Array : [1 2 3 4 5]
2D Array : [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [3]:
py_list = [1, 2, 3]
print("Python list multiplication : ", py_list * 2)

np_array = np.array([1, 2, 3])     # element wise multiplication
print("Python array multiplication : ", np_array * 2)


import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\nList operation time : ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\nNumpy operation time : ", time.time() - start)

Python list multiplication :  [1, 2, 3, 1, 2, 3]
Python array multiplication :  [2 4 6]

List operation time :  0.13412094116210938

Numpy operation time :  0.005763530731201172


### Creating array from scratch

In [4]:
zeros = np.zeros((3, 4))
print("Zeros Array:\n", zeros)

ones = np.ones((2, 3))
print("\nOnes Array:\n", ones)

full = np.full((2, 2), 9)
print("\nFull Array:\n", full)

random = np.random.random((2, 3))
print("\nRandom Array:\n", random)

sequence = np.arange(0, 11, 2)
print("\nSequence Array:\n", sequence)

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]

Full Array:
 [[9 9]
 [9 9]]

Random Array:
 [[0.10660425 0.47147905 0.02780458]
 [0.71526314 0.10657452 0.85540722]]

Sequence Array:
 [ 0  2  4  6  8 10]


### Vector, Matrix and  Tensor

In [ ]:
vector = np.array([1, 2, 3])
print(f"Vector : {vector}")



Vector : [1 2 3]
