## Numpy array operations

In [1]:
import numpy as np

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"Arr : {arr}")
print(f"Basic slicing : {arr[2:7]}")
print(f"With step : {arr[1:8:2]}")
print(f"Negative indexing : {arr[-3]}")

Arr : [1 2 3 4 5 6 7 8 9]
Basic slicing : [3 4 5 6 7]
With step : [2 4 6 8]
Negative indexing : 7


In [15]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"2D Array :\n{arr_2d}")
print(f"\nSpecific element : {arr_2d[1, 2]}")
print(f"\nEntire row (1st) : {arr_2d[1]}")
print(f"\nEntire column (1st) : {arr_2d[:, 1]}")

2D Array :
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Specific element : 6

Entire row (1st) : [4 5 6]

Entire column (1st) : [2 5 8]


## Sorting

In [24]:
unsorted = np.array([3, 5, 2, 9, 6, 4, 2, 1, 4, 3, 8])
print(f"Unsorted : {unsorted}")
print(f"Sorted : {np.sort(unsorted)}")

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print(f"\n2D array unsorted :\n{arr_2d_unsorted}")
print(f"\nSorted 2D array by column :\n{np.sort(arr_2d_unsorted, axis=0)}")
print(f"\nSorted 2D array by row :\n{np.sort(arr_2d_unsorted, axis=1)}")

Unsorted : [3 5 2 9 6 4 2 1 4 3 8]
Sorted : [1 2 2 3 3 4 4 5 6 8 9]

2D array unsorted :
[[3 1]
 [1 2]
 [2 3]]

Sorted 2D array by column :
[[1 1]
 [2 2]
 [3 3]]

Sorted 2D array by row :
[[1 3]
 [1 2]
 [2 3]]
