## Numpy array and basics
### Learn about numpy with chai aur code

In [1]:
import numpy as np

### Creating array from list

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"1D Array : {arr_1d}")

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D Array : {arr_2d}")

1D Array : [1 2 3 4 5]
2D Array : [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [3]:
py_list = [1, 2, 3]
print("Python list multiplication : ", py_list * 2)

np_array = np.array([1, 2, 3])     # element wise multiplication
print("Python array multiplication : ", np_array * 2)


import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\nList operation time : ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\nNumpy operation time : ", time.time() - start)

Python list multiplication :  [1, 2, 3, 1, 2, 3]
Python array multiplication :  [2 4 6]

List operation time :  0.13412094116210938

Numpy operation time :  0.005763530731201172


### Creating array from scratch

In [4]:
zeros = np.zeros((3, 4))
print("Zeros Array:\n", zeros)

ones = np.ones((2, 3))
print("\nOnes Array:\n", ones)

full = np.full((2, 2), 9)
print("\nFull Array:\n", full)

random = np.random.random((2, 3))
print("\nRandom Array:\n", random)

sequence = np.arange(0, 11, 2)
print("\nSequence Array:\n", sequence)

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]

Full Array:
 [[9 9]
 [9 9]]

Random Array:
 [[0.10660425 0.47147905 0.02780458]
 [0.71526314 0.10657452 0.85540722]]

Sequence Array:
 [ 0  2  4  6  8 10]


### Vector, Matrix and  Tensor

In [ ]:
vector = np.array([1, 2, 3])
print(f"Vector : {vector}")

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Matrix :\n{matrix}")

tensor = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
print(f"Tensor :\n{tensor}")

Vector : [1 2 3]
Matrix :
[[1 2 3]
 [4 5 6]]
Tensor :
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1, 2, 3], [4, 5, 6.8]])
arr3 = np.array([[1, 2, 3], [4, 5, "6"]])
print(arr)
print(f"\nShape : {arr.shape}")
print(f"Dimension : {arr.ndim}")
print(f"Size : {arr.size}")
print(f"DType Arr1 : {arr.dtype}")
print(f"DType Arr2 : {arr2.dtype}")
print(f"DType Arr3 : {arr3.dtype}")

[[1 2 3]
 [4 5 6]]

Shape : (2, 3)
Dimension : 2
Size : 6
DType Arr1 : int64
DType Arr2 : float64
DType Arr3 : <U21


### Array Reshaping

In [31]:
arr = np.arange(12)
print(f"Original array : {arr}")

reshaped = arr.reshape((3, 4))
print(f"\nReshaped array :\n{reshaped}")

flattened = reshaped.flatten()
print(f"\nFlattened array :\n{flattened}")

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print(f"\nRaveled array :\n{raveled}")

#Transpose
transpose = reshaped.T
print(f"\nTranspose array :\n{transpose}")

Original array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array :
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled array :
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpose array :
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
