# Advance operation with Business examples

In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [40]:
### Data structure : [restaurant_id, 2021, 2022, 2023, 2024]

sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],   # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],   # Beijing Bites
    [3, 200000, 230000, 260000, 300000],   # Pizza Hub
    [4, 180000, 210000, 240000, 270000],   # Burger Point
    [5, 160000, 185000, 205000, 230000]    # Chai Point
])

print("==== Zomato sales analysis ====")
print(f"\nSales data shape : {sales_data.shape}")
print(f"\nFirst three restaurant :\n{sales_data[:3]}")
# print(f"\nFirst three restaurant :\n{sales_data[:, 1:]}")

==== Zomato sales analysis ====

Sales data shape : (5, 5)

First three restaurant :
[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [60]:
# Total sales per year
print(np.sum(sales_data, axis=0))

yearly_total = np.sum(sales_data[:, 1:], axis=0)
print(yearly_total)
print(np.sum(yearly_total))


# Minimum sales per restaurant
min_sales = np.min(sales_data[:, 1:], axis=1)
print(min_sales)

print("\n")
print("=" * 60)

# Maximum sales per year
max_sales_per_year = np.max(sales_data[:, 1:], axis=0)
print(f"\nMaximum sales per year : {max_sales_per_year}")

print(f"\nSales data :\n{sales_data[:, 1:]}")

total_sales_per_rest = np.sum(sales_data[:, 1:], axis=1)
print(f"\nTotal sales per restaurant : {total_sales_per_rest}")

max_sales = np.max(total_sales_per_rest)
print(f"Maximum sales : {max_sales}")

print("\n")
print("=" * 60)


# Average sales per restaurant
avg_sales = np.mean(sales_data[:, 1:], axis=1)
print(f"\nAverage sales : {avg_sales}")


[     15  810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]
4080000
[150000 120000 200000 180000 160000]



Maximum sales per year : [200000 230000 260000 300000]

Sales data :
[[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]

Total sales per restaurant : [800000 610000 990000 900000 780000]
Maximum sales : 990000



Average sales : [200000. 152500. 247500. 225000. 195000.]
